require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PiaController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Pium. As you add validations to Pium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PiaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all pia as @pia" do
      pium = Pium.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pia)).to eq([pium])
    end
  end

  describe "GET #show" do
    it "assigns the requested pium as @pium" do
      pium = Pium.create! valid_attributes
      get :show, {:id => pium.to_param}, valid_session
      expect(assigns(:pium)).to eq(pium)
    end
  end

  describe "GET #new" do
    it "assigns a new pium as @pium" do
      get :new, {}, valid_session
      expect(assigns(:pium)).to be_a_new(Pium)
    end
  end

  describe "GET #edit" do
    it "assigns the requested pium as @pium" do
      pium = Pium.create! valid_attributes
      get :edit, {:id => pium.to_param}, valid_session
      expect(assigns(:pium)).to eq(pium)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Pium" do
        expect {
          post :create, {:pium => valid_attributes}, valid_session
        }.to change(Pium, :count).by(1)
      end

      it "assigns a newly created pium as @pium" do
        post :create, {:pium => valid_attributes}, valid_session
        expect(assigns(:pium)).to be_a(Pium)
        expect(assigns(:pium)).to be_persisted
      end

      it "redirects to the created pium" do
        post :create, {:pium => valid_attributes}, valid_session
        expect(response).to redirect_to(Pium.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved pium as @pium" do
        post :create, {:pium => invalid_attributes}, valid_session
        expect(assigns(:pium)).to be_a_new(Pium)
      end

      it "re-renders the 'new' template" do
        post :create, {:pium => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pium" do
        pium = Pium.create! valid_attributes
        put :update, {:id => pium.to_param, :pium => new_attributes}, valid_session
        pium.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pium as @pium" do
        pium = Pium.create! valid_attributes
        put :update, {:id => pium.to_param, :pium => valid_attributes}, valid_session
        expect(assigns(:pium)).to eq(pium)
      end

      it "redirects to the pium" do
        pium = Pium.create! valid_attributes
        put :update, {:id => pium.to_param, :pium => valid_attributes}, valid_session
        expect(response).to redirect_to(pium)
      end
    end

    context "with invalid params" do
      it "assigns the pium as @pium" do
        pium = Pium.create! valid_attributes
        put :update, {:id => pium.to_param, :pium => invalid_attributes}, valid_session
        expect(assigns(:pium)).to eq(pium)
      end

      it "re-renders the 'edit' template" do
        pium = Pium.create! valid_attributes
        put :update, {:id => pium.to_param, :pium => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested pium" do
      pium = Pium.create! valid_attributes
      expect {
        delete :destroy, {:id => pium.to_param}, valid_session
      }.to change(Pium, :count).by(-1)
    end

    it "redirects to the pia list" do
      pium = Pium.create! valid_attributes
      delete :destroy, {:id => pium.to_param}, valid_session
      expect(response).to redirect_to(pia_url)
    end
  end

end
